import { buildPortfolioApiFixtureKey } from "../core/api/portfolio";

export const PORTFOLIO_API_FIXTURE: Record<string, unknown> = {
  [buildPortfolioApiFixtureKey("/portfolio/command-center")]: {
    state: "ready",
    state_reason_code: "ready",
    state_reason_detail: "command_center_ready",
    as_of_ledger_at: "2026-04-18T14:30:00Z",
    as_of_market_at: "2026-04-18T14:30:00Z",
    evaluated_at: "2026-04-18T14:31:00Z",
    freshness_policy: {
      max_age_hours: 24,
    },
    net_worth_usd: "1120000",
    total_market_value_usd: "1010000",
    daily_pnl_usd: "24500",
    concentration_top5_pct: "69.31",
    insights: [
      {
        insight_id: "diversification_top5",
        title: "Diversification Check",
        message: "Top five holdings remain below elevated concentration threshold.",
        severity: "info",
      },
      {
        insight_id: "daily_pnl_positive",
        title: "Daily Strength",
        message: "Daily unrealized P&L is positive versus current pricing snapshot.",
        severity: "info",
      },
    ],
  },
  [buildPortfolioApiFixtureKey("/portfolio/summary")]: {
    as_of_ledger_at: "2026-04-18T14:30:00Z",
    pricing_snapshot_key: "snapshot-2026-04-18",
    pricing_snapshot_captured_at: "2026-04-18T14:30:00Z",
    rows: [
      {
        instrument_symbol: "MSFT",
        open_quantity: "418",
        open_cost_basis_usd: "160600",
        open_lot_count: 2,
        realized_proceeds_usd: "0",
        realized_cost_basis_usd: "0",
        realized_gain_usd: "0",
        dividend_gross_usd: "2600",
        dividend_taxes_usd: "180",
        dividend_net_usd: "2420",
        latest_close_price_usd: "430.12",
        market_value_usd: "180000",
        unrealized_gain_usd: "19400",
        unrealized_gain_pct: "12.1",
      },
      {
        instrument_symbol: "NVDA",
        open_quantity: "720",
        open_cost_basis_usd: "128800",
        open_lot_count: 2,
        realized_proceeds_usd: "0",
        realized_cost_basis_usd: "0",
        realized_gain_usd: "0",
        dividend_gross_usd: "0",
        dividend_taxes_usd: "0",
        dividend_net_usd: "0",
        latest_close_price_usd: "497.11",
        market_value_usd: "160000",
        unrealized_gain_usd: "31200",
        unrealized_gain_pct: "24.2",
      },
      {
        instrument_symbol: "COST",
        open_quantity: "185",
        open_cost_basis_usd: "128900",
        open_lot_count: 1,
        realized_proceeds_usd: "0",
        realized_cost_basis_usd: "0",
        realized_gain_usd: "0",
        dividend_gross_usd: "1200",
        dividend_taxes_usd: "84",
        dividend_net_usd: "1116",
        latest_close_price_usd: "756.42",
        market_value_usd: "140000",
        unrealized_gain_usd: "11100",
        unrealized_gain_pct: "8.6",
      },
      {
        instrument_symbol: "AMD",
        open_quantity: "310",
        open_cost_basis_usd: "111200",
        open_lot_count: 2,
        realized_proceeds_usd: "0",
        realized_cost_basis_usd: "0",
        realized_gain_usd: "0",
        dividend_gross_usd: "0",
        dividend_taxes_usd: "0",
        dividend_net_usd: "0",
        latest_close_price_usd: "198.31",
        market_value_usd: "120000",
        unrealized_gain_usd: "8800",
        unrealized_gain_pct: "7.9",
      },
      {
        instrument_symbol: "PANW",
        open_quantity: "130",
        open_cost_basis_usd: "92800",
        open_lot_count: 1,
        realized_proceeds_usd: "0",
        realized_cost_basis_usd: "0",
        realized_gain_usd: "0",
        dividend_gross_usd: "0",
        dividend_taxes_usd: "0",
        dividend_net_usd: "0",
        latest_close_price_usd: "304.12",
        market_value_usd: "100000",
        unrealized_gain_usd: "7200",
        unrealized_gain_pct: "7.8",
      },
      {
        instrument_symbol: "TXN",
        open_quantity: "156",
        open_cost_basis_usd: "89000",
        open_lot_count: 1,
        realized_proceeds_usd: "0",
        realized_cost_basis_usd: "0",
        realized_gain_usd: "0",
        dividend_gross_usd: "1100",
        dividend_taxes_usd: "77",
        dividend_net_usd: "1023",
        latest_close_price_usd: "610.55",
        market_value_usd: "95000",
        unrealized_gain_usd: "6000",
        unrealized_gain_pct: "6.7",
      },
      {
        instrument_symbol: "LULU",
        open_quantity: "90",
        open_cost_basis_usd: "74600",
        open_lot_count: 1,
        realized_proceeds_usd: "0",
        realized_cost_basis_usd: "0",
        realized_gain_usd: "0",
        dividend_gross_usd: "0",
        dividend_taxes_usd: "0",
        dividend_net_usd: "0",
        latest_close_price_usd: "421.07",
        market_value_usd: "80000",
        unrealized_gain_usd: "5400",
        unrealized_gain_pct: "7.2",
      },
      {
        instrument_symbol: "UNH",
        open_quantity: "128",
        open_cost_basis_usd: "82300",
        open_lot_count: 2,
        realized_proceeds_usd: "0",
        realized_cost_basis_usd: "0",
        realized_gain_usd: "0",
        dividend_gross_usd: "2000",
        dividend_taxes_usd: "140",
        dividend_net_usd: "1860",
        latest_close_price_usd: "593.12",
        market_value_usd: "75000",
        unrealized_gain_usd: "-7200",
        unrealized_gain_pct: "-8.8",
      },
      {
        instrument_symbol: "AAPL",
        open_quantity: "142",
        open_cost_basis_usd: "57400",
        open_lot_count: 2,
        realized_proceeds_usd: "0",
        realized_cost_basis_usd: "0",
        realized_gain_usd: "0",
        dividend_gross_usd: "700",
        dividend_taxes_usd: "49",
        dividend_net_usd: "651",
        latest_close_price_usd: "430.85",
        market_value_usd: "60000",
        unrealized_gain_usd: "5400",
        unrealized_gain_pct: "9.4",
      },
    ],
  },
  [buildPortfolioApiFixtureKey("/portfolio/hierarchy", { group_by: "sector" })]: {
    as_of_ledger_at: "2026-04-18T14:30:00Z",
    group_by: "sector",
    pricing_snapshot_key: "snapshot-2026-04-18",
    pricing_snapshot_captured_at: "2026-04-18T14:30:00Z",
    groups: [
      {
        group_key: "technology",
        group_label: "Technology",
        asset_count: 2,
        total_market_value_usd: "815000",
        total_profit_loss_usd: "76100",
        total_change_pct: "10.3",
        assets: [
          {
            instrument_symbol: "MSFT",
            sector_label: "Technology",
            open_quantity: "418",
            open_cost_basis_usd: "160600",
            avg_price_usd: "384.02",
            current_price_usd: "430.12",
            market_value_usd: "180000",
            profit_loss_usd: "19400",
            change_pct: "12.1",
            lot_count: 2,
            lots: [
              {
                lot_id: 101,
                opened_on: "2024-01-12",
                original_qty: "240",
                remaining_qty: "180",
                unit_cost_basis_usd: "362.50",
                total_cost_basis_usd: "87000",
                market_value_usd: "77400",
                profit_loss_usd: "10400",
              },
              {
                lot_id: 102,
                opened_on: "2024-07-03",
                original_qty: "238",
                remaining_qty: "238",
                unit_cost_basis_usd: "308.45",
                total_cost_basis_usd: "73400",
                market_value_usd: "102600",
                profit_loss_usd: "9000",
              },
            ],
          },
          {
            instrument_symbol: "AMD",
            sector_label: "Technology",
            open_quantity: "310",
            open_cost_basis_usd: "111200",
            avg_price_usd: "358.71",
            current_price_usd: "198.31",
            market_value_usd: "120000",
            profit_loss_usd: "8800",
            change_pct: "7.9",
            lot_count: 2,
            lots: [
              {
                lot_id: 301,
                opened_on: "2024-03-19",
                original_qty: "160",
                remaining_qty: "160",
                unit_cost_basis_usd: "240.55",
                total_cost_basis_usd: "38488",
                market_value_usd: "31700",
                profit_loss_usd: "3212",
              },
              {
                lot_id: 302,
                opened_on: "2024-08-08",
                original_qty: "150",
                remaining_qty: "150",
                unit_cost_basis_usd: "485.41",
                total_cost_basis_usd: "72712",
                market_value_usd: "88800",
                profit_loss_usd: "5588",
              },
            ],
          },
        ],
      },
      {
        group_key: "consumer",
        group_label: "Consumer Staples",
        asset_count: 2,
        total_market_value_usd: "220000",
        total_profit_loss_usd: "16500",
        total_change_pct: "8.1",
        assets: [
          {
            instrument_symbol: "COST",
            sector_label: "Consumer Staples",
            open_quantity: "185",
            open_cost_basis_usd: "128900",
            avg_price_usd: "696.22",
            current_price_usd: "756.42",
            market_value_usd: "140000",
            profit_loss_usd: "11100",
            change_pct: "8.6",
            lot_count: 1,
            lots: [
              {
                lot_id: 701,
                opened_on: "2024-04-10",
                original_qty: "185",
                remaining_qty: "185",
                unit_cost_basis_usd: "696.22",
                total_cost_basis_usd: "128900",
                market_value_usd: "140000",
                profit_loss_usd: "11100",
              },
            ],
          },
          {
            instrument_symbol: "LULU",
            sector_label: "Consumer Staples",
            open_quantity: "90",
            open_cost_basis_usd: "74600",
            avg_price_usd: "396.25",
            current_price_usd: "421.07",
            market_value_usd: "80000",
            profit_loss_usd: "5400",
            change_pct: "7.2",
            lot_count: 1,
            lots: [
              {
                lot_id: 702,
                opened_on: "2024-05-07",
                original_qty: "90",
                remaining_qty: "90",
                unit_cost_basis_usd: "396.25",
                total_cost_basis_usd: "74600",
                market_value_usd: "80000",
                profit_loss_usd: "5400",
              },
            ],
          },
        ],
      },
      {
        group_key: "healthcare",
        group_label: "Healthcare",
        asset_count: 1,
        total_market_value_usd: "75000",
        total_profit_loss_usd: "-7200",
        total_change_pct: "-8.8",
        assets: [
          {
            instrument_symbol: "UNH",
            sector_label: "Healthcare",
            open_quantity: "128",
            open_cost_basis_usd: "82300",
            avg_price_usd: "642.18",
            current_price_usd: "593.12",
            market_value_usd: "75000",
            profit_loss_usd: "-7200",
            change_pct: "-8.8",
            lot_count: 2,
            lots: [
              {
                lot_id: 801,
                opened_on: "2024-02-06",
                original_qty: "80",
                remaining_qty: "80",
                unit_cost_basis_usd: "657.22",
                total_cost_basis_usd: "52580",
                market_value_usd: "47450",
                profit_loss_usd: "-5130",
              },
              {
                lot_id: 802,
                opened_on: "2024-09-17",
                original_qty: "48",
                remaining_qty: "48",
                unit_cost_basis_usd: "619.17",
                total_cost_basis_usd: "29720",
                market_value_usd: "27550",
                profit_loss_usd: "-2070",
              },
            ],
          },
        ],
      },
    ],
  },
  [buildPortfolioApiFixtureKey("/portfolio/contribution", { period: "YTD" })]: {
    as_of_ledger_at: "2026-04-18T14:30:00Z",
    period: "YTD",
    rows: [
      {
        instrument_symbol: "NVDA",
        contribution_pnl_usd: "31200",
        contribution_pct: "31.2",
      },
      {
        instrument_symbol: "MSFT",
        contribution_pnl_usd: "19400",
        contribution_pct: "19.4",
      },
      {
        instrument_symbol: "COST",
        contribution_pnl_usd: "11100",
        contribution_pct: "11.1",
      },
      {
        instrument_symbol: "AMD",
        contribution_pnl_usd: "8800",
        contribution_pct: "8.8",
      },
      {
        instrument_symbol: "PANW",
        contribution_pnl_usd: "7200",
        contribution_pct: "7.2",
      },
      {
        instrument_symbol: "TXN",
        contribution_pnl_usd: "6000",
        contribution_pct: "6.0",
      },
      {
        instrument_symbol: "LULU",
        contribution_pnl_usd: "5400",
        contribution_pct: "5.4",
      },
      {
        instrument_symbol: "AAPL",
        contribution_pnl_usd: "5400",
        contribution_pct: "5.4",
      },
      {
        instrument_symbol: "UNH",
        contribution_pnl_usd: "-7200",
        contribution_pct: "-7.2",
      },
    ],
  },
  [buildPortfolioApiFixtureKey("/portfolio/lots/MSFT")]: {
    as_of_ledger_at: "2026-04-18T14:30:00Z",
    instrument_symbol: "MSFT",
    lots: [
      {
        lot_id: 101,
        opened_on: "2024-01-12",
        original_qty: "240",
        remaining_qty: "180",
        total_cost_basis_usd: "87000",
        unit_cost_basis_usd: "362.50",
        dispositions: [
          {
            sell_transaction_id: 9001,
            disposition_date: "2025-11-14",
            matched_qty: "60",
            matched_cost_basis_usd: "21750",
            sell_gross_amount_usd: "25380",
          },
        ],
      },
      {
        lot_id: 102,
        opened_on: "2024-07-03",
        original_qty: "238",
        remaining_qty: "238",
        total_cost_basis_usd: "73400",
        unit_cost_basis_usd: "308.45",
        dispositions: [],
      },
    ],
  },
  [buildPortfolioApiFixtureKey("/portfolio/lots/AAPL")]: {
    as_of_ledger_at: "2026-04-18T14:30:00Z",
    instrument_symbol: "AAPL",
    lots: [
      {
        lot_id: 1,
        opened_on: "2024-01-12",
        original_qty: "72",
        remaining_qty: "44",
        total_cost_basis_usd: "17500",
        unit_cost_basis_usd: "398.55",
        dispositions: [
          {
            sell_transaction_id: 10001,
            disposition_date: "2025-08-07",
            matched_qty: "28",
            matched_cost_basis_usd: "11160",
            sell_gross_amount_usd: "12980",
          },
        ],
      },
      {
        lot_id: 2,
        opened_on: "2024-07-03",
        original_qty: "98",
        remaining_qty: "98",
        total_cost_basis_usd: "39900",
        unit_cost_basis_usd: "408.16",
        dispositions: [],
      },
    ],
  },
  [buildPortfolioApiFixtureKey("/portfolio/time-series", {
    period: "90D",
    scope: "portfolio",
  })]: {
    as_of_ledger_at: "2026-04-18T14:30:00Z",
    period: "90D",
    frequency: "1D",
    timezone: "UTC",
    points: [
      {
        captured_at: "2026-01-20T00:00:00Z",
        portfolio_value_usd: "962000",
        pnl_usd: "0",
        benchmark_sp500_value_usd: "962000",
        benchmark_nasdaq100_value_usd: "962000",
      },
      {
        captured_at: "2026-02-21T00:00:00Z",
        portfolio_value_usd: "986500",
        pnl_usd: "24500",
        benchmark_sp500_value_usd: "975100",
        benchmark_nasdaq100_value_usd: "980400",
      },
      {
        captured_at: "2026-03-23T00:00:00Z",
        portfolio_value_usd: "1004200",
        pnl_usd: "42200",
        benchmark_sp500_value_usd: "989900",
        benchmark_nasdaq100_value_usd: "997500",
      },
      {
        captured_at: "2026-04-18T00:00:00Z",
        portfolio_value_usd: "1010000",
        pnl_usd: "48000",
        benchmark_sp500_value_usd: "993000",
        benchmark_nasdaq100_value_usd: "1005000",
      },
    ],
  },
  [buildPortfolioApiFixtureKey("/portfolio/time-series", {
    period: "YTD",
    scope: "portfolio",
  })]: {
    as_of_ledger_at: "2026-04-18T14:30:00Z",
    period: "YTD",
    frequency: "1D",
    timezone: "UTC",
    points: [
      {
        captured_at: "2026-01-02T00:00:00Z",
        portfolio_value_usd: "940000",
        pnl_usd: "0",
        benchmark_sp500_value_usd: "940000",
        benchmark_nasdaq100_value_usd: "940000",
      },
      {
        captured_at: "2026-02-17T00:00:00Z",
        portfolio_value_usd: "985000",
        pnl_usd: "45000",
        benchmark_sp500_value_usd: "970000",
        benchmark_nasdaq100_value_usd: "979000",
      },
      {
        captured_at: "2026-04-18T00:00:00Z",
        portfolio_value_usd: "1010000",
        pnl_usd: "70000",
        benchmark_sp500_value_usd: "993000",
        benchmark_nasdaq100_value_usd: "1005000",
      },
    ],
  },
  [buildPortfolioApiFixtureKey("/portfolio/time-series", {
    instrument_symbol: "MSFT",
    period: "90D",
    scope: "instrument_symbol",
  })]: {
    as_of_ledger_at: "2026-04-18T14:30:00Z",
    period: "90D",
    frequency: "1D",
    timezone: "UTC",
    points: [
      {
        captured_at: "2026-01-02T00:00:00Z",
        portfolio_value_usd: "360000",
        pnl_usd: "0",
        benchmark_sp500_value_usd: "360000",
        benchmark_nasdaq100_value_usd: "360000",
      },
      {
        captured_at: "2026-02-17T00:00:00Z",
        portfolio_value_usd: "372500",
        pnl_usd: "12500",
        benchmark_sp500_value_usd: "367500",
        benchmark_nasdaq100_value_usd: "369200",
      },
      {
        captured_at: "2026-04-18T00:00:00Z",
        portfolio_value_usd: "390000",
        pnl_usd: "30000",
        benchmark_sp500_value_usd: "380000",
        benchmark_nasdaq100_value_usd: "385000",
      },
    ],
  },
  [buildPortfolioApiFixtureKey("/portfolio/health-synthesis", {
    period: "90D",
    profile_posture: "balanced",
    scope: "portfolio",
  })]: {
    as_of_ledger_at: "2026-04-18T14:30:00Z",
    scope: "portfolio",
    instrument_symbol: null,
    period: "90D",
    profile_posture: "balanced",
    health_score: 76,
    health_label: "healthy",
    threshold_policy_version: "health_v1_20260330",
    pillars: [
      {
        pillar_id: "growth",
        label: "Growth",
        score: 82,
        status: "favorable",
        metrics: [
          {
            metric_id: "cagr",
            label: "CAGR",
            value_display: "14.2%",
            score: 82,
            contribution: "supporting",
          },
        ],
      },
      {
        pillar_id: "risk",
        label: "Risk",
        score: 68,
        status: "caution",
        metrics: [
          {
            metric_id: "max_drawdown",
            label: "Max drawdown",
            value_display: "-12.8%",
            score: 68,
            contribution: "penalizing",
          },
        ],
      },
    ],
    key_drivers: [
      {
        metric_id: "concentration_top5",
        label: "Top 5 concentration",
        direction: "penalizing",
        impact_points: 18,
        rationale: "Concentration remains elevated but within policy bounds.",
        value_display: "69.3%",
      },
      {
        metric_id: "relative_strength",
        label: "Relative strength",
        direction: "supporting",
        impact_points: 14,
        rationale: "Portfolio keeps a modest spread advantage versus benchmark.",
        value_display: "+2.1%",
      },
    ],
    health_caveats: [
      "Freshness is direct for market prices, but some research metrics remain unavailable.",
    ],
    core_metric_ids: ["cagr", "cumulative_return"],
    advanced_metric_ids: ["max_drawdown"],
  },
  [buildPortfolioApiFixtureKey("/portfolio/health-synthesis", {
    instrument_symbol: "MSFT",
    period: "90D",
    profile_posture: "balanced",
    scope: "instrument_symbol",
  })]: {
    as_of_ledger_at: "2026-04-18T14:30:00Z",
    scope: "instrument_symbol",
    instrument_symbol: "MSFT",
    period: "90D",
    profile_posture: "balanced",
    health_score: 81,
    health_label: "healthy",
    threshold_policy_version: "health_v1_20260330",
    pillars: [
      {
        pillar_id: "growth",
        label: "Growth",
        score: 86,
        status: "favorable",
        metrics: [
          {
            metric_id: "relative_strength",
            label: "Relative strength",
            value_display: "+12.1%",
            score: 86,
            contribution: "supporting",
          },
        ],
      },
      {
        pillar_id: "risk",
        label: "Risk",
        score: 70,
        status: "caution",
        metrics: [
          {
            metric_id: "beta",
            label: "Beta",
            value_display: "1.31",
            score: 70,
            contribution: "penalizing",
          },
        ],
      },
    ],
    key_drivers: [
      {
        metric_id: "trend",
        label: "Trend quality",
        direction: "supporting",
        impact_points: 15,
        rationale: "Uptrend remains intact with positive follow-through.",
        value_display: "Constructive",
      },
      {
        metric_id: "drawdown",
        label: "Drawdown amplitude",
        direction: "penalizing",
        impact_points: 10,
        rationale: "Recovery is good but not yet fully reset.",
        value_display: "-8.8%",
      },
    ],
    health_caveats: [],
    core_metric_ids: ["relative_strength"],
    advanced_metric_ids: ["beta"],
  },
};
